/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carnew.glb 
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/porsche-carrera-gt-concept-2000-replica-a4ee4d4177794a93b29382fce4010d52
Title: Porsche Carrera GT Concept 2000 Replica
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Carnew=(props)=> {
  const { nodes, materials } = useGLTF('./model/carnew.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.056, 0]} scale={1.053}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.CarreraGT} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ENGINEgrill} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Smoke} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blackaluminium} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.blackchrome} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.blackmatte} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.blackmatte2} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.blackplastic} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.bottom} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.brakedisc} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.brakelight} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.buttons} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.carSHADOW} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.centrebrakelampglass} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.concept} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.detailschrome} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.detailsmatte} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.detailsplastic} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.diffuzer} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.emblem} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.engine} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.enginechrome1} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.enginechrome2} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.enginehead} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.exhametal1} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.exhametal2} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.exhaustchrome} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.exhausthole} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.floor} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.floormat} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.floormat2} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.foglight} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.frontbumperplastic} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.grill1} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.grill2} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.grillrear} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.headlightglass} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.headlights1} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.headlights2} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.interiormatte} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.interiormirror} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.interiorplastic} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.needforspeed} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.plateREAR} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.radiator} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.rim1} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.rim2} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.seatbelt} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.sidemirrors} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.splitter} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.suport1} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.suport2} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.suportlogo} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.tire} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.tireSIDE} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.turnsignalF} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.turnsignalS} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.wfins} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.wsins} />
      </group>
    </group>
  )
}

export default Carnew

useGLTF.preload('./model/carnew.glb')
