/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Porche.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Porche.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Object_69" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_68" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_63" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_60" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_59" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_46" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_45" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_44" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_39" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_34" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Object_16" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <group name="Spoiler_1" position={[0, 5.491, -9.972]} rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
          <group name="4d8b5d19e0cb436896a422dbfd5fd5a2fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Universal_spoiler_1" rotation={[-Math.PI / 2, 0, 0]} scale={[100, 70.719, 100]}>
                <mesh name="Universal_spoiler_1_Carbon_0" geometry={nodes.Universal_spoiler_1_Carbon_0.geometry} material={materials.Carbon} />
                <mesh name="Universal_spoiler_1_Feet_0" geometry={nodes.Universal_spoiler_1_Feet_0.geometry} material={materials.Feet} />
              </group>
            </group>
          </group>
        </group>
        <group name="Spoiler_2" position={[0, 4.65, -8.81]} rotation={[-Math.PI / 2, 0, 0]} scale={0.624}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_0" position={[2.427, 0.018, -1.315]} rotation={[0.385, 0, 0]} scale={[0.051, 0.907, 0.442]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['Material.001']} position={[-1.54, 0, 0]} />
              </group>
              <group name="Cube002_3" position={[0.228, 2.597, -0.189]} rotation={[0.039, 0, 0]} scale={[5.572, 0.043, 1.064]}>
                <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials['Material.002']} position={[-0.047, 0, 0]} />
              </group>
              <group name="Cube003_2" position={[6.009, 2.799, 0]} scale={[0.085, 0.926, 1.664]}>
                <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['Material.003']} position={[-3.07, 0, 0]} />
              </group>
              <group name="Cube004_4" position={[-5.409, 2.799, 0]} scale={[0.085, 0.926, 1.664]}>
                <mesh name="Object_12001" geometry={nodes.Object_12001.geometry} material={materials['Material.003']} position={[-3.07, 0, 0]} />
              </group>
              <group name="Cube005_5" position={[-1.393, 0.018, -1.315]} rotation={[0.385, 0, 0]} scale={[0.051, 0.907, 0.442]}>
                <mesh name="Object_14001" geometry={nodes.Object_14001.geometry} material={materials['Material.001']} position={[-17.884, 0, 0]} />
              </group>
              <group name="Cube_1" position={[0.317, 2.799, 0]} scale={[5.71, 0.055, 1.362]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.004']} position={[-0.046, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Spoiler_3" position={[0, 5.589, -9.666]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
          <group name="e79f5967d0b04bbf986de8022d9c6b9dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Plane" position={[0, -40.689, 3.731]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 16.373, 100]}>
                <mesh name="Plane_Carbon_0" geometry={nodes.Plane_Carbon_0.geometry} material={materials['Carbon.001']} position={[0, 0.066, 0.063]} />
                <mesh name="Plane_Feet_0" geometry={nodes.Plane_Feet_0.geometry} material={materials['Feet.001']} position={[0, 0.066, 0.063]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Tyre_2" position={[4.05, 1.587, 6.754]} rotation={[-Math.PI / 2, 0, 0]} scale={0.032}>
          <group name="bottom_left_tyre001" position={[7.98, 433.818, 0]}>
            <mesh name="Object_2001" geometry={nodes.Object_2001.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_3001" geometry={nodes.Object_3001.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_4003" geometry={nodes.Object_4003.geometry} material={materials['default']} />
          </group>
          <group name="bottom_right_tyre001" position={[-255.832, 433.818, 0]} rotation={[Math.PI, 0, 0]} scale={-1}>
            <mesh name="Object_2003" geometry={nodes.Object_2003.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_3003" geometry={nodes.Object_3003.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_4005" geometry={nodes.Object_4005.geometry} material={materials['default']} />
          </group>
          <group name="top_left_tyre001" position={[7.98, 0, 0]}>
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_4002" geometry={nodes.Object_4002.geometry} material={materials['default']} />
          </group>
          <group name="top_right_tyre001" position={[-255.832, 0, 0]} rotation={[Math.PI, 0, 0]} scale={-1}>
            <mesh name="Object_2002" geometry={nodes.Object_2002.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_3002" geometry={nodes.Object_3002.geometry} material={materials.RIM_UNITED} />
            <mesh name="Object_4004" geometry={nodes.Object_4004.geometry} material={materials['default']} />
          </group>
        </group>
        <group name="Tyre_1" position={[0.302, -0.108, -1.034]} rotation={[-Math.PI / 2, 0, 0]} scale={4.88}>
          <group name="bottom_left_tyre002" position={[0, 2.885, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode003" position={[0.208, 0, 0]}>
              <group name="mycar-wheelbrakeFtL002" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0001" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0001'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Plastic_0001" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0001'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Rims_0001" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0001'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Silver_0001" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0001'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0002" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0002'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0003" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0003'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
              </group>
            </group>
          </group>
          <group name="bottom_right_tyre002" position={[-0.125, 2.885, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01}>
            <group name="RootNode005" position={[0.208, 0, 0]}>
              <group name="mycar-wheelbrakeFtL004" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0003" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0003'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Plastic_0003" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0003'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Rims_0003" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0003'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Silver_0003" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0003'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0006" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0006'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0007" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0007'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
              </group>
            </group>
          </group>
          <group name="top_left_tyre002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode002" position={[0.718, 0, 0]}>
              <group name="mycar-wheelbrakeFtL001" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Plastic_0" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Rims_0" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Silver_0" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0001" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0001'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
              </group>
            </group>
          </group>
          <group name="top_right_tyre002" position={[-0.125, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01}>
            <group name="RootNode004" position={[0.718, 0, 0]}>
              <group name="mycar-wheelbrakeFtL003" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0002" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0002'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Plastic_0002" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0002'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Rims_0002" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0002'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Silver_0002" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0002'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0004" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0004'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                <mesh name="mycar-wheelbrakeFtL001_Tyre_0005" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0005'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Tyre_3" position={[-3.257, 0, -7.284]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={4.122}>
          <group name="root001" position={[-0.015, 1.855, 0.388]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.879}>
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="CTWheelFtR_2" rotation={[-0.002, Math.PI / 2, 0]}>
                <group name="rim004_0" position={[-0.187, 0.012, -0.006]}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.007']} />
                </group>
                <group name="wheel002_1">
                  <mesh name="Object_10002" geometry={nodes.Object_10002.geometry} material={materials['Material.008']} />
                  <mesh name="Object_11001" geometry={nodes.Object_11001.geometry} material={materials['Material.008']} />
                  <mesh name="Object_12002" geometry={nodes.Object_12002.geometry} material={materials['Material.008']} />
                  <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['Material.008']} />
                  <mesh name="Object_8002" geometry={nodes.Object_8002.geometry} material={materials['Material.008']} />
                  <mesh name="Object_9001" geometry={nodes.Object_9001.geometry} material={materials['Material.008']} />
                </group>
              </group>
            </group>
          </group>
          <group name="root002" position={[3.404, 1.855, 0.388]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.879}>
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="CTWheelFtR_2001" rotation={[-0.002, Math.PI / 2, 0]}>
                <group name="rim004_0001" position={[-0.187, 0.012, -0.006]}>
                  <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['Material.007']} />
                </group>
                <group name="wheel002_1001">
                  <mesh name="Object_10003" geometry={nodes.Object_10003.geometry} material={materials['Material.008']} />
                  <mesh name="Object_11002" geometry={nodes.Object_11002.geometry} material={materials['Material.008']} />
                  <mesh name="Object_12003" geometry={nodes.Object_12003.geometry} material={materials['Material.008']} />
                  <mesh name="Object_7002" geometry={nodes.Object_7002.geometry} material={materials['Material.008']} />
                  <mesh name="Object_8003" geometry={nodes.Object_8003.geometry} material={materials['Material.008']} />
                  <mesh name="Object_9002" geometry={nodes.Object_9002.geometry} material={materials['Material.008']} />
                </group>
              </group>
            </group>
          </group>
          <group name="root003" position={[-0.015, -0.273, 0.388]} scale={0.879}>
            <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
              <group name="CTWheelFtR_2002" rotation={[-0.002, Math.PI / 2, 0]}>
                <group name="rim004_0002" position={[-0.187, 0.012, -0.006]}>
                  <mesh name="Object_5002" geometry={nodes.Object_5002.geometry} material={materials['Material.007']} />
                </group>
                <group name="wheel002_1002">
                  <mesh name="Object_10004" geometry={nodes.Object_10004.geometry} material={materials['Material.008']} />
                  <mesh name="Object_11003" geometry={nodes.Object_11003.geometry} material={materials['Material.008']} />
                  <mesh name="Object_12004" geometry={nodes.Object_12004.geometry} material={materials['Material.008']} />
                  <mesh name="Object_7003" geometry={nodes.Object_7003.geometry} material={materials['Material.008']} />
                  <mesh name="Object_8004" geometry={nodes.Object_8004.geometry} material={materials['Material.008']} />
                  <mesh name="Object_9003" geometry={nodes.Object_9003.geometry} material={materials['Material.008']} />
                </group>
              </group>
            </group>
          </group>
          <group name="root004" position={[3.404, -0.273, 0.388]} scale={0.879}>
            <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
              <group name="CTWheelFtR_2003" rotation={[-0.002, Math.PI / 2, 0]}>
                <group name="rim004_0003" position={[-0.187, 0.012, -0.006]}>
                  <mesh name="Object_5003" geometry={nodes.Object_5003.geometry} material={materials['Material.007']} />
                </group>
                <group name="wheel002_1003">
                  <mesh name="Object_10005" geometry={nodes.Object_10005.geometry} material={materials['Material.008']} />
                  <mesh name="Object_11004" geometry={nodes.Object_11004.geometry} material={materials['Material.008']} />
                  <mesh name="Object_12005" geometry={nodes.Object_12005.geometry} material={materials['Material.008']} />
                  <mesh name="Object_7004" geometry={nodes.Object_7004.geometry} material={materials['Material.008']} />
                  <mesh name="Object_8005" geometry={nodes.Object_8005.geometry} material={materials['Material.008']} />
                  <mesh name="Object_9004" geometry={nodes.Object_9004.geometry} material={materials['Material.008']} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.wsins} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={0.62} />
        <mesh name="front_mirror" geometry={nodes.front_mirror.geometry} material={materials.wfins} position={[-0.005, 4.692, 3.205]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="metallic_things2" geometry={nodes.metallic_things2.geometry} material={materials.turnsignalS} position={[-0.006, 3.327, 4.782]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.turnsignalF} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.suportlogo} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.suport2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.suport1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="car_black_metallic_sides" geometry={nodes.car_black_metallic_sides.geometry} material={materials.splitter} position={[-0.095, 0.379, 4.656]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.seatbelt} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.radiator} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="number_plate" geometry={nodes.number_plate.geometry} material={materials.plateREAR} position={[-0.003, 2.056, -11.388]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.needforspeed} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="interior_wheel" geometry={nodes.interior_wheel.geometry} material={materials.interiorplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.interiormirror} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="carpet_near_gear" geometry={nodes.carpet_near_gear.geometry} material={materials.interiormatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="black_metallic_steering" geometry={nodes.black_metallic_steering.geometry} material={materials.interior} position={[0.916, 4.319, 1.712]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_bumper_net" geometry={nodes.back_bumper_net.geometry} material={materials.grillrear} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.grill2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.grill1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="front_bumper" geometry={nodes.front_bumper.geometry} material={materials.frontbumperplastic} position={[0.01, 1.048, 11.176]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="behind_net_carpet" geometry={nodes.behind_net_carpet.geometry} material={materials.floormat2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="leg_carpet" geometry={nodes.leg_carpet.geometry} material={materials.floormat} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.exhausthole} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.exhametal2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.exhametal1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_both_small_wings" geometry={nodes.back_both_small_wings.geometry} material={materials.enginehead} position={[-0.006, 4.587, -4.921]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.enginechrome2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="metallic_thing_under_wings" geometry={nodes.metallic_thing_under_wings.geometry} material={materials.enginechrome1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_inner_material" geometry={nodes.back_inner_material.geometry} material={materials.engine} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="All_logos" geometry={nodes.All_logos.geometry} material={materials.emblem} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_bumper" geometry={nodes.back_bumper.geometry} material={materials.diffuzer} position={[-0.004, 1.447, -10.901]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="metallic_parts_suppressor" geometry={nodes.metallic_parts_suppressor.geometry} material={materials.detailsplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="seat_belt_top" geometry={nodes.seat_belt_top.geometry} material={materials.detailsmatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="metallic_things" geometry={nodes.metallic_things.geometry} material={materials.detailschrome} position={[-0.006, 2.157, 6.652]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.concept} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="white_material" geometry={nodes.white_material.geometry} material={materials.chrome} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="metallic_above_seats" geometry={nodes.metallic_above_seats.geometry} material={materials.centrebrakelampglass} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="steering_buttons" geometry={nodes.steering_buttons.geometry} material={materials.buttons} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="tyre_inner_material" geometry={nodes.tyre_inner_material.geometry} material={materials.brakedisc} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.bottom} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="black_metallic_things" geometry={nodes.black_metallic_things.geometry} material={materials.blackplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.blackmatte2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.blackmatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.blackchrome} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.blackaluminium} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_6} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Main_Body" geometry={nodes.Main_Body.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} position={[-0.106, 3.081, 0.227]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_net_behind_seat" geometry={nodes.back_net_behind_seat.geometry} material={materials.ENGINEgrill} position={[-0.006, 4.375, -5.714]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="Camera_gt_logo" geometry={nodes.Camera_gt_logo.geometry} material={materials.CarreraGT} position={[-0.106, 3.214, -11.478]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_tyre" geometry={nodes.top_right_tyre.geometry} material={materials.tire} position={[-4.347, 1.599, 6.712]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_tyre" geometry={nodes.top_left_tyre.geometry} material={materials.tire} position={[4.335, 1.599, 6.768]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_left_tyre" geometry={nodes.bottom_left_tyre.geometry} material={materials.tire} position={[4.143, 1.591, -7.244]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_right_tyre" geometry={nodes.bottom_right_tyre.geometry} material={materials.tire} position={[-4.151, 1.591, -7.303]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_tyre_outer" geometry={nodes.top_right_tyre_outer.geometry} material={materials.rim1} position={[-4.898, 1.599, 6.739]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_right_tyre_outer" geometry={nodes.bottom_right_tyre_outer.geometry} material={materials.rim1} position={[-4.822, 1.591, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_left_tyre_outer" geometry={nodes.bottom_left_tyre_outer.geometry} material={materials.rim1} position={[4.815, 1.591, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_tyre_outer" geometry={nodes.top_left_tyre_outer.geometry} material={materials.rim1} position={[4.886, 1.599, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_tyre_inner" geometry={nodes.top_right_tyre_inner.geometry} material={materials.rim2} position={[-4.704, 1.554, 6.74]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_tyre_inner" geometry={nodes.top_left_tyre_inner.geometry} material={materials.rim2} position={[4.692, 1.554, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_left_tyre_inner" geometry={nodes.bottom_left_tyre_inner.geometry} material={materials.rim2} position={[4.391, 1.543, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_right_tyre_inner" geometry={nodes.bottom_right_tyre_inner.geometry} material={materials.rim2} position={[-4.399, 1.544, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="left_head_light" geometry={nodes.left_head_light.geometry} material={materials.headlightglass} position={[3.497, 2.977, 9.821]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="right_head_light" geometry={nodes.right_head_light.geometry} material={materials.headlightglass} position={[-3.505, 2.977, 9.822]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_right_head_light" geometry={nodes.back_right_head_light.geometry} material={materials.brakelight} position={[-3.622, 3.431, -10.349]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_left_head_light" geometry={nodes.back_left_head_light.geometry} material={materials.brakelight} position={[3.603, 3.431, -10.35]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="back_middle_head_light" geometry={nodes.back_middle_head_light.geometry} material={materials.brakelight} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="right_nitro" geometry={nodes.right_nitro.geometry} material={materials.exhaustchrome} position={[-1.92, 1.928, -11.38]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="left_nitro" geometry={nodes.left_nitro.geometry} material={materials.exhaustchrome} position={[1.914, 1.928, -11.379]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="right_side_mirror" geometry={nodes.right_side_mirror.geometry} material={materials.sidemirrors} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="left_side_mirror" geometry={nodes.left_side_mirror.geometry} material={materials.sidemirrors} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="front_small_light_left" geometry={nodes.front_small_light_left.geometry} material={materials.foglight} position={[2.433, 1.105, 11.462]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="front_small_light_right" geometry={nodes.front_small_light_right.geometry} material={materials.foglight} position={[-2.446, 1.105, 11.461]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_head_light_big" geometry={nodes.top_right_head_light_big.geometry} material={materials.headlights1} position={[-3.884, 3.132, 9.045]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_head_light_big" geometry={nodes.top_left_head_light_big.geometry} material={materials.headlights1} position={[3.871, 3.132, 9.046]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_middle_head_light_big" geometry={nodes.top_middle_head_light_big.geometry} material={materials.headlights1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_head_light_small" geometry={nodes.top_right_head_light_small.geometry} material={materials.headlights2} position={[-3.213, 2.987, 9.433]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_head_light_small" geometry={nodes.top_left_head_light_small.geometry} material={materials.headlights2} position={[3.2, 2.987, 9.434]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_right_tyre_branding" geometry={nodes.top_right_tyre_branding.geometry} material={materials.tireSIDE} position={[-4.347, 1.599, 6.739]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="top_left_tyre_branding" geometry={nodes.top_left_tyre_branding.geometry} material={materials.tireSIDE} position={[4.335, 1.599, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_left_tyre_branding" geometry={nodes.bottom_left_tyre_branding.geometry} material={materials.tireSIDE} position={[4.143, 1.591, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} />
        <mesh name="bottom_right_tyre_branding" geometry={nodes.bottom_right_tyre_branding.geometry} material={materials.tireSIDE} position={[-4.151, 1.591, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} />
      </group>
    </group>
  )
}

useGLTF.preload('/Porche.glb')
