/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Car_F.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import Car from './Car'

const Car_F=(props)=> {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./model/Car_F.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode">
          <group name="Object_73_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_73_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_73_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_73_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.wsins} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_72_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_72_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_72_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_72_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.wfins} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_71_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_71_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_71_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_71_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.turnsignalS} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_70_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_70_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_70_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_70_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.turnsignalF} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_69_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_69_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_69_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_69_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.tireSIDE} />
                </group>
              </group>
            </group>
          </group>
          <group name="top_right_tyre_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="top_right_tyre_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="top_right_tyre_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="top_right_tyre_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="top_right_tyre" geometry={nodes.top_right_tyre.geometry} material={materials.tire} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_67_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_67_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_67_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_67_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.suportlogo} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_66_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_66_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_66_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_66_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.suport2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_65_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_65_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_65_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_65_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.suport1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_64_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_64_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_64_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_64_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.splitter} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_63_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_63_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_63_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_63_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.sidemirrors} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_62_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_62_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_62_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_62_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.seatbelt} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_61_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_61_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_61_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_61_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_60_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_60_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_60_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_60_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.rim2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_59_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_59_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_59_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_59_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.rim1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_58_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_58_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_58_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_58_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.radiator} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_57_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_57_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_57_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_57_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_56_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_56_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_56_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_56_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.plateREAR} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_55_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_55_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_55_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_55_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_54_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_54_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_54_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_54_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.needforspeed} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_53_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_53_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_53_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_53_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.interiorplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_52_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_52_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_52_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_52_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.interiormirror} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_51_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_51_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_51_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_51_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.interiormatte} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_50_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_50_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_50_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_50_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_49_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_49_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_49_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_49_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_48_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_48_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_48_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_48_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.interior} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_47_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_47_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_47_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_47_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_46_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_46_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_46_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_46_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.headlights2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_45_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_45_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_45_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_45_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.headlights1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_44_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_44_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_44_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_44_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.headlightglass} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_43_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_43_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_43_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_43_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.grillrear} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_42_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_42_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_42_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_42_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.grill2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_41_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_41_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_41_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_41_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.grill1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_40_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_40_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_40_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_40_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.frontbumperplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_39_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_39_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_39_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_39_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.foglight} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_38_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_38_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_38_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_38_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.floormat2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_37_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_37_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_37_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_37_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.floormat} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_35_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_35_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_35_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_35_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.exhausthole} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_34_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_34_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_34_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_34_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.exhaustchrome} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_33_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_33_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_33_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_33_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_32_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_32_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_32_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_32_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.exhametal2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_31_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_31_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_31_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_31_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.exhametal1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_30_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_30_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_30_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_30_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.enginehead} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_29_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_29_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_29_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_29_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.enginechrome2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_28_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_28_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_28_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_28_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.enginechrome1} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_27_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_27_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_27_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_27_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.engine} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_26_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_26_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_26_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_26_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.emblem} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_25_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_25_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_25_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_25_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.diffuzer} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_24_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_24_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_24_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_24_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.detailsplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_23_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_23_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_23_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_23_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.detailsmatte} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_22_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_22_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_22_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_22_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.detailschrome} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_21_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_21_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_21_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_21_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.concept} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_20_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_20_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_20_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_20_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.chrome} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_19_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_19_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_19_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_19_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.centrebrakelampglass} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_17_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_17_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_17_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_17_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.buttons} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_16_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_16_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_16_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_16_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.brakelight} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_15_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_15_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_15_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_15_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.brakedisc} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_14_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_14_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_14_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_14_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.bottom} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_13_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_13_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_13_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_13_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.blackplastic} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_12_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_12_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_12_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_12_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.blackmatte2} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_11_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_11_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_11_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_11_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.blackmatte} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_10_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_10_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_10_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_10_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.blackchrome} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_9_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_9_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_9_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_9_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.blackaluminium} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_8_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_8_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_8_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_8_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_6_material} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_7_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_7_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_7_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_7_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_5_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_5_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_5_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_5_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_4_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_4_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_4_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_4_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_3_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_3_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_3_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_3_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.ENGINEgrill} />
                </group>
              </group>
            </group>
          </group>
          <group name="Object_2_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Object_2_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Object_2_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Object_2_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.CarreraGT} />
                </group>
              </group>
            </group>
          </group>
          <group name="Top_Left_tyre_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="Top_Left_tyre_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Top_Left_tyre_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="Top_Left_tyre_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="Top_Left_tyre" geometry={nodes.Top_Left_tyre.geometry} material={materials.tire} />
                </group>
              </group>
            </group>
          </group>
          <group name="bottom_left_tyre_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="bottom_left_tyre_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="bottom_left_tyre_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="bottom_left_tyre_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="bottom_left_tyre" geometry={nodes.bottom_left_tyre.geometry} material={materials.tire} />
                </group>
              </group>
            </group>
          </group>
          <group name="bottom_right_tyre_$AssimpFbx$_Translation" position={[-1.259, -2.173, -8.946]}>
            <group name="bottom_right_tyre_$AssimpFbx$_PreRotation" rotation={[-Math.PI / 2, 0, 0]}>
              <group name="bottom_right_tyre_$AssimpFbx$_Rotation" rotation={[0, 0.007, -Math.PI]}>
                <group name="bottom_right_tyre_$AssimpFbx$_Scaling" scale={18.542}>
                  <mesh name="bottom_right_tyre" geometry={nodes.bottom_right_tyre.geometry} material={materials.tire} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/Car_F.glb')

export default Car_F
