/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Carblender.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Carblender = (props) =>{
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./model/Carblender.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.blackaluminium} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_6} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.wsins} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.wfins} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.turnsignalS} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.turnsignalF} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.tireSIDE} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Bottom_Right_Tyre" geometry={nodes.Bottom_Right_Tyre.geometry} material={materials.tire} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.suportlogo} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.suport2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.suport1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.splitter} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.sidemirrors} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.seatbelt} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.rim2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.rim1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.radiator} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.plateREAR} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.needforspeed} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.interiorplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.interiormirror} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.interiormatte} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.interior} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.headlights2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.headlights1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.headlightglass} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.grillrear} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.grill2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.grill1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.frontbumperplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.foglight} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.floormat2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.floormat} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.exhausthole} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.exhaustchrome} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.exhametal2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.exhametal1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.enginehead} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.ENGINEgrill} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.enginechrome2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.enginechrome1} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.engine} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.emblem} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.diffuzer} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.detailsplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.detailsmatte} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.detailschrome} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.concept} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.chrome} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.CarreraGT} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.centrebrakelampglass} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.buttons} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.brakelight} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.brakedisc} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.bottom} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.blackplastic} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.blackmatte2} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.blackmatte} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.blackchrome} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={0.572} />
        <mesh name="Top_Right_Tyre" geometry={nodes.Top_Right_Tyre.geometry} material={materials.tire} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={5.129} />
        <mesh name="Top_Left_Tyre" geometry={nodes.Top_Left_Tyre.geometry} material={materials.tire} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={5.129} />
        <mesh name="Bottom_Left_Tyre" geometry={nodes.Bottom_Left_Tyre.geometry} material={materials.tire} position={[-0.082, -0.136, -0.065]} rotation={[0, 0, -0.056]} scale={5.129} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Carblender.glb')

export default Carblender
