/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carfinal.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Carfinal =(props)=> {
  const { nodes, materials } = useGLTF('./model/carfinal.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_71.geometry} material={materials.carobj_wsins} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_70.geometry} material={materials.carobj_wfins} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.carobj_turnsignalS} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_68.geometry} material={materials.carobj_turnsignalF} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_67.geometry} material={materials.carobj_tireSIDE} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Right_Tyre.geometry} material={materials.carobj_tire} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials.carobj_suportlogo} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_64.geometry} material={materials.carobj_suport2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials.carobj_suport1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_62.geometry} material={materials.carobj_splitter} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_61.geometry} material={materials.carobj_sidemirrors} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_60.geometry} material={materials.carobj_seatbelt} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_59.geometry} material={materials.carobj_rimEMBLEM} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Left_ORim.geometry} material={materials.carobj_rim2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Right_ORim.geometry} material={materials.carobj_rim1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials.carobj_radiator} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_55.geometry} material={materials.carobj_plateREDlamp} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_54.geometry} material={materials.carobj_plateREAR} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials.carobj_plateLAMP1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_52.geometry} material={materials.carobj_needforspeed} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_51.geometry} material={materials.carobj_interiorplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_50.geometry} material={materials.carobj_interiormirror} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_49.geometry} material={materials.carobj_interiormatte} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.carobj_interiorgrayplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_47.geometry} material={materials.carobj_interiorblackplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials.carobj_interior} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_45.geometry} material={materials.carobj_headlightwhiteplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.carobj_headlights2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_43.geometry} material={materials.carobj_headlights1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Front_Left_Light.geometry} material={materials.carobj_headlightglass} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_41.geometry} material={materials.carobj_grillrear} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials.carobj_grill2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_39.geometry} material={materials.carobj_grill1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_38.geometry} material={materials.carobj_frontbumperplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials.carobj_foglight} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_36.geometry} material={materials.carobj_floormat2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.carobj_floormat} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_33.geometry} material={materials.carobj_exhausthole} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_32.geometry} material={materials.carobj_exhaustchrome} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.carobj_exhaustbronze} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_30.geometry} material={materials.carobj_exhametal2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_29.geometry} material={materials.carobj_exhametal1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials.carobj_enginehead} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_27.geometry} material={materials.carobj_enginechrome2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.carobj_enginechrome1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials.carobj_engine} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials.carobj_emblem} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.carobj_diffuzer} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials.carobj_detailsplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials.carobj_detailsmatte} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.carobj_detailschrome} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.carobj_concept} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.carobj_chrome} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials.carobj_centrebrakelampglass} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.carobj_buttons} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Back_Left_HeadLight.geometry} material={materials.carobj_brakelight} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.carobj_brakedisc} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.carobj_bottom} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.carobj_blackplastic} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.carobj_blackmatte2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_9.geometry} material={materials.carobj_blackmatte} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials.carobj_blackchrome} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.carobj_blackaluminium} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.carobj_material_6} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Front_Glass.geometry} material={materials.carobj_material} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Main_Body.geometry} material={materials.carobj_Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_2.geometry} material={materials.carobj_PORSCHEenginelogo} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_1.geometry} material={materials.carobj_ENGINEgrill} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Object_0.geometry} material={materials.carobj_CarreraGT} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Right_Tyre.geometry} material={materials.carobj_tire} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Left_Tyre.geometry} material={materials.carobj_tire} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Left_Tyre.geometry} material={materials.carobj_tire} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Right_ORim.geometry} material={materials.carobj_rim1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Left_ORim.geometry} material={materials.carobj_rim1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Left_ORim_node.geometry} material={materials.carobj_rim1} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Right_IRim.geometry} material={materials.carobj_rim2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Top_Left_ORim001.geometry} material={materials.carobj_rim2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Bottom_Right_ORim001.geometry} material={materials.carobj_rim2} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Back_Right_HeadLight.geometry} material={materials.carobj_brakelight} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Back_Center_HeadLight.geometry} material={materials.carobj_brakelight} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Front_Right_Light.geometry} material={materials.carobj_headlightglass} scale={19.305} />
          </group>
        </group>
      </group>
      <group position={[1.114, -1.579, 5.574]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[0, -0.06, 0]}>
            <mesh geometry={nodes.Back_Right_Nitro.geometry} material={materials.carobj_exhaustchrome} scale={19.305} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/carfinal.glb')

export default Carfinal