/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carglb.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Carglb=(props)=> {
  <ambientLight/>
  const { nodes, materials } = useGLTF('./model/carglb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_71_node.geometry} material={materials.carobj_wsins} />
      <mesh geometry={nodes.Object_70_node.geometry} material={materials.carobj_wfins} />
      <mesh geometry={nodes.Object_69_node.geometry} material={materials.carobj_turnsignalS} />
      <mesh geometry={nodes.Object_68_node.geometry} material={materials.carobj_turnsignalF} />
      <mesh geometry={nodes.Object_67_node.geometry} material={materials.carobj_tireSIDE} />
      <mesh geometry={nodes.Bottom_Right_Tyre_node.geometry} material={materials.carobj_tire} />
      <mesh geometry={nodes.Object_65_node.geometry} material={materials.carobj_suportlogo} />
      <mesh geometry={nodes.Object_64_node.geometry} material={materials.carobj_suport2} />
      <mesh geometry={nodes.Object_63_node.geometry} material={materials.carobj_suport1} />
      <mesh geometry={nodes.Object_62_node.geometry} material={materials.carobj_splitter} />
      <mesh geometry={nodes.Object_61_node.geometry} material={materials.carobj_sidemirrors} />
      <mesh geometry={nodes.Object_60_node.geometry} material={materials.carobj_seatbelt} />
      <mesh geometry={nodes.Object_59_node.geometry} material={materials.carobj_rimEMBLEM} />
      <mesh geometry={nodes.Bottom_Left_ORim_node.geometry} material={materials.carobj_rim2} />
      <mesh geometry={nodes.Bottom_Right_ORim_node.geometry} material={materials.carobj_rim1} />
      <mesh geometry={nodes.Object_56_node.geometry} material={materials.carobj_radiator} />
      <mesh geometry={nodes.Object_55_node.geometry} material={materials.carobj_plateREDlamp} />
      <mesh geometry={nodes.Object_54_node.geometry} material={materials.carobj_plateREAR} />
      <mesh geometry={nodes.Object_53_node.geometry} material={materials.carobj_plateLAMP1} />
      <mesh geometry={nodes.Object_52_node.geometry} material={materials.carobj_needforspeed} />
      <mesh geometry={nodes.Object_51_node.geometry} material={materials.carobj_interiorplastic} />
      <mesh geometry={nodes.Object_50_node.geometry} material={materials.carobj_interiormirror} />
      <mesh geometry={nodes.Object_49_node.geometry} material={materials.carobj_interiormatte} />
      <mesh geometry={nodes.Object_48_node.geometry} material={materials.carobj_interiorgrayplastic} />
      <mesh geometry={nodes.Object_47_node.geometry} material={materials.carobj_interiorblackplastic} />
      <mesh geometry={nodes.Object_46_node.geometry} material={materials.carobj_interior} />
      <mesh geometry={nodes.Object_45_node.geometry} material={materials.carobj_headlightwhiteplastic} />
      <mesh geometry={nodes.Object_44_node.geometry} material={materials.carobj_headlights2} />
      <mesh geometry={nodes.Object_43_node.geometry} material={materials.carobj_headlights1} />
      <mesh geometry={nodes.Front_Left_Light_node.geometry} material={materials.carobj_headlightglass} />
      <mesh geometry={nodes.Object_41_node.geometry} material={materials.carobj_grillrear} />
      <mesh geometry={nodes.Object_40_node.geometry} material={materials.carobj_grill2} />
      <mesh geometry={nodes.Object_39_node.geometry} material={materials.carobj_grill1} />
      <mesh geometry={nodes.Object_38_node.geometry} material={materials.carobj_frontbumperplastic} />
      <mesh geometry={nodes.Object_37_node.geometry} material={materials.carobj_foglight} />
      <mesh geometry={nodes.Object_36_node.geometry} material={materials.carobj_floormat2} />
      <mesh geometry={nodes.Object_35_node.geometry} material={materials.carobj_floormat} />
      <mesh geometry={nodes.Object_33_node.geometry} material={materials.carobj_exhausthole} />
      <mesh geometry={nodes.Object_32_node.geometry} material={materials.carobj_exhaustchrome} />
      <mesh geometry={nodes.Object_31_node.geometry} material={materials.carobj_exhaustbronze} />
      <mesh geometry={nodes.Object_30_node.geometry} material={materials.carobj_exhametal2} />
      <mesh geometry={nodes.Object_29_node.geometry} material={materials.carobj_exhametal1} />
      <mesh geometry={nodes.Object_28_node.geometry} material={materials.carobj_enginehead} />
      <mesh geometry={nodes.Object_27_node.geometry} material={materials.carobj_enginechrome2} />
      <mesh geometry={nodes.Object_26_node.geometry} material={materials.carobj_enginechrome1} />
      <mesh geometry={nodes.Object_25_node.geometry} material={materials.carobj_engine} />
      <mesh geometry={nodes.Object_24_node.geometry} material={materials.carobj_emblem} />
      <mesh geometry={nodes.Object_23_node.geometry} material={materials.carobj_diffuzer} />
      <mesh geometry={nodes.Object_22_node.geometry} material={materials.carobj_detailsplastic} />
      <mesh geometry={nodes.Object_21_node.geometry} material={materials.carobj_detailsmatte} />
      <mesh geometry={nodes.Object_20_node.geometry} material={materials.carobj_detailschrome} />
      <mesh geometry={nodes.Object_19_node.geometry} material={materials.carobj_concept} />
      <mesh geometry={nodes.Object_18_node.geometry} material={materials.carobj_chrome} />
      <mesh geometry={nodes.Object_17_node.geometry} material={materials.carobj_centrebrakelampglass} />
      <mesh geometry={nodes.Object_15_node.geometry} material={materials.carobj_buttons} />
      <mesh geometry={nodes.Back_Left_HeadLight_node.geometry} material={materials.carobj_brakelight} />
      <mesh geometry={nodes.Object_13_node.geometry} material={materials.carobj_brakedisc} />
      <mesh geometry={nodes.Object_12_node.geometry} material={materials.carobj_bottom} />
      <mesh geometry={nodes.Object_11_node.geometry} material={materials.carobj_blackplastic} />
      <mesh geometry={nodes.Object_10_node.geometry} material={materials.carobj_blackmatte2} />
      <mesh geometry={nodes.Object_9_node.geometry} material={materials.carobj_blackmatte} />
      <mesh geometry={nodes.Object_8_node.geometry} material={materials.carobj_blackchrome} />
      <mesh geometry={nodes.Object_7_node.geometry} material={materials.carobj_blackaluminium} />
      <mesh geometry={nodes.Object_6_node.geometry} material={materials.carobj_material_6} />
      <mesh geometry={nodes.Front_Glass_node.geometry} material={materials.carobj_material} />
      <mesh geometry={nodes.Main_Body_node.geometry} material={materials.carobj_Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} />
      <mesh geometry={nodes.Object_2_node.geometry} material={materials.carobj_PORSCHEenginelogo} />
      <mesh geometry={nodes.Object_1_node.geometry} material={materials.carobj_ENGINEgrill} />
      <mesh geometry={nodes.Object_0_node.geometry} material={materials.carobj_CarreraGT} />
      <mesh geometry={nodes.Top_Right_Tyre_node.geometry} material={materials.carobj_tire} />
      <mesh geometry={nodes.Top_Left_Tyre_node.geometry} material={materials.carobj_tire} />
      <mesh geometry={nodes.Bottom_Left_Tyre_node.geometry} material={materials.carobj_tire} />
      <mesh geometry={nodes.Top_Right_ORim_node.geometry} material={materials.carobj_rim1} />
      <mesh geometry={nodes.Top_Left_ORim_node.geometry} material={materials.carobj_rim1} />
      <mesh geometry={nodes.Bottom_Left_ORim_node_0.geometry} material={materials.carobj_rim1} />
      <mesh geometry={nodes.Top_Right_IRim_node.geometry} material={materials.carobj_rim2} />
      <mesh geometry={nodes.Top_Left_ORim001_node.geometry} material={materials.carobj_rim2} />
      <mesh geometry={nodes.Bottom_Right_ORim001_node.geometry} material={materials.carobj_rim2} />
      <mesh geometry={nodes.Back_Right_HeadLight_node.geometry} material={materials.carobj_brakelight} />
      <mesh geometry={nodes.Back_Center_HeadLight_node.geometry} material={materials.carobj_brakelight} />
      <mesh geometry={nodes.Front_Right_Light_node.geometry} material={materials.carobj_headlightglass} />
      <mesh geometry={nodes.Back_Right_Nitro_node.geometry} material={materials.carobj_exhaustchrome} />
    </group>
  )
}

useGLTF.preload('./model/carglb.glb')

export default Carglb
