/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cartemp.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Cartemp =(props) =>{
  const { nodes, materials } = useGLTF('./model/cartemp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_73.geometry} material={materials.wsins} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_72.geometry} material={materials.wfins} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_71.geometry} material={materials.turnsignalS} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_70.geometry} material={materials.turnsignalF} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_69.geometry} material={materials.tireSIDE} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_68.geometry} material={materials.tire} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_67.geometry} material={materials.suportlogo} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_66.geometry} material={materials.suport2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_65.geometry} material={materials.suport1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_64.geometry} material={materials.splitter} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_63.geometry} material={materials.sidemirrors} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_62.geometry} material={materials.seatbelt} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_60.geometry} material={materials.rim2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_59.geometry} material={materials.rim1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_58.geometry} material={materials.radiator} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_56.geometry} material={materials.plateREAR} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_54.geometry} material={materials.needforspeed} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_53.geometry} material={materials.interiorplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_52.geometry} material={materials.interiormirror} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_51.geometry} material={materials.interiormatte} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_48.geometry} material={materials.interior} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_46.geometry} material={materials.headlights2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_45.geometry} material={materials.headlights1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_44.geometry} material={materials.headlightglass} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_43.geometry} material={materials.grillrear} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_42.geometry} material={materials.grill2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_41.geometry} material={materials.grill1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_40.geometry} material={materials.frontbumperplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_39.geometry} material={materials.foglight} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_38.geometry} material={materials.floormat2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_37.geometry} material={materials.floormat} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_35.geometry} material={materials.exhausthole} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_34.geometry} material={materials.exhaustchrome} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_32.geometry} material={materials.exhametal2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_31.geometry} material={materials.exhametal1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_30.geometry} material={materials.enginehead} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_29.geometry} material={materials.enginechrome2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_28.geometry} material={materials.enginechrome1} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.engine} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_26.geometry} material={materials.emblem} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_25.geometry} material={materials.diffuzer} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_24.geometry} material={materials.detailsplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_23.geometry} material={materials.detailsmatte} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_22.geometry} material={materials.detailschrome} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_21.geometry} material={materials.concept} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.chrome} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_19.geometry} material={materials.centrebrakelampglass} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.buttons} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_16.geometry} material={materials.brakelight} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_15.geometry} material={materials.brakedisc} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_14.geometry} material={materials.bottom} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_13.geometry} material={materials.blackplastic} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.blackmatte2} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_11.geometry} material={materials.blackmatte} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.blackchrome} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.blackaluminium} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_8.geometry} material={materials.material_6_material} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.material} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.ENGINEgrill} scale={24.398} />
        </group>
      </group>
      <group position={[-0.149, -4.645, 6.181]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.CarreraGT} scale={24.398} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/cartemp.glb')

export default Cartemp
