/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Porche.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, Environment, MeshReflectorMaterial } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import * as THREE from "three"
import { useControls } from 'leva';




const Porche = (props) => {
  const { bodyColor, carSpoiler, tyretype, CarRough, CarMetal, castShadow, receiveShadow } = props;
  const { scene } = useThree();
  const group = React.useRef()
  const top_right_tyre_Ref1 = useRef();
  const top_right_tyre_Ref2 = useRef();
  const top_right_tyre_Ref3 = useRef();
  const top_right_tyre_Ref4 = useRef();
  const top_left_tyre_Ref1 = useRef();
  const top_left_tyre_Ref2 = useRef();
  const top_left_tyre_Ref3 = useRef();
  const top_left_tyre_Ref4 = useRef();
  const [spoiler1, setspoiler1] = useState(false);
  const [spoiler2, setspoiler2] = useState(false);
  const [spoiler3, setspoiler3] = useState(false);
  const [tyre1, settyre1] = useState(false);
  const [tyre2, settyre2] = useState(false);
  const [tyre3, settyre3] = useState(false);
  const [tyre1toggle, settyre1toggle] = useState(false)
  const model = useGLTF("./model/Porche.glb")


  const { nodes, materials, animations } = useGLTF('./model/Porche.glb')
  const { actions } = useAnimations(animations, group)

  useFrame((_, delta) => {

    
    
  })




  useEffect(() => {
    if (materials.brakelight) {
      materials.brakelight.metalness = 1;
      materials.brakelight.roughness = 0.3;
      materials.brakelight.envMapIntensity = 1.2;
      materials.brakelight.needsUpdate = true;
    }
  }, [materials]);
  useEffect(() => {
    if (materials.emblem) {
      materials.emblem.metalness = 1;          // full metallic shine
      materials.emblem.roughness = 0.15;       // slightly smooth surface
      materials.emblem.envMapIntensity = 1.5;  // makes reflections pop
      materials.emblem.clearcoat = 1;          // extra gloss
      materials.emblem.clearcoatRoughness = 0.05;
      materials.emblem.needsUpdate = true;
    }
  }, [materials]);
  useEffect(() => {
    if (materials.CarreraGT) {
      materials.CarreraGT.metalness = 1;              // full metallic
      materials.CarreraGT.roughness = 0.15;           // smooth surface
      materials.CarreraGT.envMapIntensity = 1.8;      // strong reflections
      materials.CarreraGT.clearcoat = 1;              // glossy finish
      materials.CarreraGT.clearcoatRoughness = 0.04;  // slight surface texture
      materials.CarreraGT.needsUpdate = true;
    }
  }, [materials]);

  useEffect(() => {
    if (materials.tire) {
      materials.tire.metalness = 0.1;           // rubber isn't metallic
      materials.tire.roughness = 0.9;         // matte finish
      materials.tire.envMapIntensity = 0.2;   // slight environmental reflections
      materials.tire.needsUpdate = true;      // apply changes
    }
  }, []);

  useEffect(() => {
    if (materials.Carbon) {
      materials.Carbon.metalness = 0.5;        // shiny, metallic carbon look
      materials.Carbon.roughness = 0.5;        // smooth surface
      materials.Carbon.envMapIntensity = 1;    // strong environment reflections
      materials.Carbon.needsUpdate = true;
    }

    if (materials.Feet) {
      materials.Feet.metalness = 0.6;          // semi-metallic feet
      materials.Feet.roughness = 0.4;          // a bit rough
      materials.Feet.envMapIntensity = 0.5;    // medium reflections
      materials.Feet.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.tireSIDE) {
      materials.tireSIDE.metalness = 0.4;       // very subtle metal feel, almost none
      materials.tireSIDE.roughness = 0.75;       // smoother than outer tread
      materials.tireSIDE.envMapIntensity = 0.6;  // gentle ambient reflections
      materials.tireSIDE.needsUpdate = true;     // ensure changes are applied
    }
  }, []);

  useEffect(() => {
    if (materials.headlights2) {
      materials.headlights2.metalness = 0.2;          // low metallic to keep glass-like feel
      materials.headlights2.roughness = 0.1;          // smooth and shiny surface
      materials.headlights2.emissive = new THREE.Color(0xffffff);  // white glow
      materials.headlights2.emissiveIntensity = 0.6;  // subtle glow brightness
      materials.headlights2.transparent = true;       // allow some transparency
      materials.headlights2.opacity = 0.9;             // slightly see-through for realism
      materials.headlights2.envMapIntensity = 1.0;    // reflections from environment
      materials.headlights2.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.headlights1) {
      materials.headlights1.metalness = 0.3;            // a bit more metallic for polished housing
      materials.headlights1.roughness = 0.05;           // very smooth, shiny surface
      materials.headlights1.emissive = new THREE.Color(0xffffff); // subtle white glow
      materials.headlights1.emissiveIntensity = 0.4;    // light glow but not overpowering
      materials.headlights1.transparent = true;         // to simulate glass transparency
      materials.headlights1.opacity = 0.85;              // mostly transparent
      materials.headlights1.envMapIntensity = 1.2;      // strong reflection of env map
      materials.headlights1.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.ENGINEgrill) {
      materials.ENGINEgrill.metalness = 0.5;          // stronger metallic feel
      materials.ENGINEgrill.roughness = 0.25;         // smoother for shinier surface
      materials.ENGINEgrill.color = new THREE.Color(0x888888);  // lighter grey metal tint
      materials.ENGINEgrill.envMapIntensity = 2.0;    // stronger environment reflections
      materials.ENGINEgrill.side = THREE.DoubleSide;  // render both sides, important for net
      materials.ENGINEgrill.needsUpdate = true;
    }
  }, []);


  useEffect(() => {
    if (materials.enginehead) {
      materials.enginehead.metalness = 0.9;    // very metallic
      materials.enginehead.roughness = 0.25;   // slightly smooth but with texture
      materials.enginehead.color = new THREE.Color(0xb0b8bf); // light gray metallic tint
      materials.enginehead.envMapIntensity = 1.2; // moderate reflections
      materials.enginehead.needsUpdate = true;
    }
  }, []);


  useEffect(() => {
    if (materials.blackmatte) {
      materials.blackmatte.metalness = 0.7;              // gives it a metallic base
      materials.blackmatte.roughness = 0.5;              // slightly matte finish, not glossy
      materials.blackmatte.color = new THREE.Color(0x0a0a0a); // deep black tone
      materials.blackmatte.envMapIntensity = 1.0;        // mild reflection
      materials.blackmatte.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.enginechrome1) {
      materials.enginechrome1.metalness = 1.0;                        // fully metallic
      materials.enginechrome1.roughness = 0.15;                      // sleek with slight texture
      materials.enginechrome1.color = new THREE.Color("white");     // soft off-white for realism
      materials.enginechrome1.envMapIntensity = 1.8;                 // nice reflective highlights
      materials.enginechrome1.needsUpdate = true;
    }
  }, []);


  useEffect(() => {
    if (materials.interior) {
      materials.interior.metalness = 0.1;                          // slight metallic tint (for luxury feel)
      materials.interior.roughness = 0.5;                          // leather-like surface
      materials.interior.color = new THREE.Color(0x1a1a1a);        // rich black
      materials.interior.envMapIntensity = 1.2;                    // subtle interior reflection
      materials.interior.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.interiorplastic) {
      materials.interiorplastic.metalness = 0.2;                        // low metallic value (plastic)
      materials.interiorplastic.roughness = 0.6;                        // high roughness for matte feel
      materials.interiorplastic.color = new THREE.Color(0x2c2c2c);     // deep charcoal black
      materials.interiorplastic.envMapIntensity = 0.8;                 // mild environmental reflection
      materials.interiorplastic.needsUpdate = true;
    }
  }, []);
  useEffect(() => {
    if (materials.floormat2) {
      materials.floormat2.metalness = 0;                                // no metallic properties
      materials.floormat2.roughness = 1;                                // full roughness (no gloss)
      materials.floormat2.color = new THREE.Color(0x1a1a1a);            // deep black/charcoal
      materials.floormat2.envMapIntensity = 0.2;                        // very minimal reflection
      materials.floormat2.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.floormat) {
      materials.floormat.metalness = 0;                               // no metallic quality
      materials.floormat.roughness = 0.9;                               // fully rough (no shine)

      materials.floormat.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.engine) {
      materials.engine.metalness = 0.2;                      // not metallic
      materials.engine.roughness = 1;                      // matte finish, no reflections

      materials.engine.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.bottom) {
      materials.bottom.metalness = 0.2;                      // No metallic effect
      materials.bottom.roughness = 1;                      // Fully matte, no reflection

      materials.bottom.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.wfins) {
      materials.wfins.transparent = true;
      materials.wfins.opacity = 0.01; // Lowered for more transparency
      materials.wfins.metalness = 0;
      materials.wfins.roughness = 0.03; // Still keeps that soft realistic blur
      materials.wfins.envMapIntensity = 1.4; // Slightly stronger reflections
      materials.wfins.color = new THREE.Color(0xffffff); // Pure neutral tone
      materials.wfins.side = THREE.DoubleSide;
      materials.wfins.depthWrite = false;
      materials.wfins.needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    if (materials.Material) {
      materials.Material.metalness = 0.3;
      materials.Material.roughness = 0.7;
      materials.Material.color.set('#2c2c2c');
      materials.Material.envMapIntensity = 0.3;
      materials.Material.needsUpdate = true;
    }

    if (materials['Material.001']) {
      materials['Material.001'].metalness = 0.5;
      materials['Material.001'].roughness = 0.6;
      materials['Material.001'].color.set('#4f4f4f');
      materials['Material.001'].envMapIntensity = 0.4;
      materials['Material.001'].needsUpdate = true;
    }

    if (materials['Material.002']) {
      materials['Material.002'].metalness = 0.8;
      materials['Material.002'].roughness = 0.4;
      materials['Material.002'].color.set('black');
      materials['Material.002'].envMapIntensity = 0.5;
      materials['Material.002'].needsUpdate = true;
    }

    if (materials['Material.003']) {
      materials['Material.003'].metalness = 0.6;
      materials['Material.003'].roughness = 0.3;
      materials['Material.003'].color.set('#293822');
      materials['Material.003'].envMapIntensity = 0.5;
      materials['Material.003'].needsUpdate = true;
    }
  }, []);

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = castShadow
        child.receiveShadow = receiveShadow
        child.material.needsUpdate = true
      }
    })
  }, [scene, castShadow, receiveShadow])

  useEffect(() => {
    if (materials['Carbon.001']) {
      materials['Carbon.001'].metalness = 0.7;
      materials['Carbon.001'].roughness = 0.4;
      materials['Carbon.001'].color.set('#121212');
      materials['Carbon.001'].envMapIntensity = 0.6;
      materials['Carbon.001'].needsUpdate = true;
    }

    if (materials['Feet.001']) {
      materials['Feet.001'].metalness = 0.4;
      materials['Feet.001'].roughness = 0.6;
      materials['Feet.001'].color.set('#292929');
      materials['Feet.001'].envMapIntensity = 0.3;
      materials['Feet.001'].needsUpdate = true;
    }
    if (materials.RIM_UNITED) {
      materials.RIM_UNITED.metalness = 1;                             // fully metallic
      materials.RIM_UNITED.roughness = 0.1;                           // slightly glossy
      materials.RIM_UNITED.envMapIntensity = 1.0;                     // strong environment reflection
      materials.RIM_UNITED.needsUpdate = true;
    }

    if (materials.Rims) {
      materials.Rims.metalness = 1;                              // full metallic shine
      materials.Rims.roughness = 0.05;
      materials.Rims.envMapIntensity = 0.8;                      // decent environment reflection
      materials.Rims.needsUpdate = true;
    }

    if (materials.Tyre) {
      materials.Tyre.metalness = 0;                                // no metallic shine
      materials.Tyre.roughness = 1;                               // high roughness = matte finish
      materials.Tyre.envMapIntensity = 0;                           // no reflection
      materials.Tyre.needsUpdate = true;
    }

    const rimMaterial = materials['Material.007'];

    if (rimMaterial) {
      rimMaterial.color = new THREE.Color(0x666666);           // mid-tone brushed steel
      rimMaterial.metalness = 0.8;                              // strong metallic look
      rimMaterial.roughness = 0.1;                              // semi-gloss, not too shiny
      rimMaterial.envMapIntensity = 1;                          // visible reflections (from env map)
      rimMaterial.needsUpdate = true;
    }






  }, []);



  useEffect(() => {
    if (carSpoiler === "spoiler1") {
      setspoiler1(true);
    }
    else {
      setspoiler1(false)
    }
    if (carSpoiler === "spoiler2") {
      setspoiler2(true);
    }
    else {
      setspoiler2(false)
    }
    if (carSpoiler === "spoiler3") {
      setspoiler3(true);
    }
    else {
      setspoiler3(false)
    }
    if (tyretype === "tyre1") {
      settyre1(true)
    } else {
      settyre1(false)
    }

    if (tyretype == "default") {
      settyre1toggle(true)
    }
    else {
      settyre1toggle(false);
    }
    if (tyretype == "tyre2") {
      settyre2(true)
    }
    else {
      settyre2(false);
    }
    if (tyretype == "tyre3") {
      settyre3(true)
    }
    else {
      settyre3(false);
    }
  })







  return (
    <>

      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Object_69" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_68" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_63" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_60" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_59" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_46" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_45" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_44" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_39" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_34" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <group name="Object_16" position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.wsins} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={0.62} />
          <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.turnsignalF} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.suportlogo} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.suport2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.suport1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.seatbelt} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.rimEMBLEM} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.radiator} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.plateREDlamp} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="number_plate" geometry={nodes.number_plate.geometry} material={materials.plateREAR} position={[-0.003, 2.056, -11.388]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.plateLAMP1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.needforspeed} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.interiormirror} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="carpet_near_gear" geometry={nodes.carpet_near_gear.geometry} material={materials.interiormatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.interiorgrayplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.interiorblackplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.headlightwhiteplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="back_bumper_net" geometry={nodes.back_bumper_net.geometry} material={materials.grillrear} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.grill1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.exhausthole} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.exhaustbronze} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.exhametal2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.exhametal1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.enginechrome2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="back_bumper" geometry={nodes.back_bumper.geometry} material={materials.diffuzer} position={[-0.004, 1.447, -10.901]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="metallic_parts_suppressor" geometry={nodes.metallic_parts_suppressor.geometry} material={materials.detailsplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="seat_belt_top" geometry={nodes.seat_belt_top.geometry} material={materials.detailsmatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="metallic_things" geometry={nodes.metallic_things.geometry} material={materials.detailschrome} position={[-0.006, 2.157, 6.652]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.concept} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="white_material" geometry={nodes.white_material.geometry} material={materials.chrome} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="metallic_above_seats" geometry={nodes.metallic_above_seats.geometry} material={materials.centrebrakelampglass} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="steering_buttons" geometry={nodes.steering_buttons.geometry} material={materials.buttons} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="tyre_inner_material" geometry={nodes.tyre_inner_material.geometry} material={materials.brakedisc} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="black_metallic_things" geometry={nodes.black_metallic_things.geometry} material={materials.blackplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.blackmatte2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.blackchrome} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.blackaluminium} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_6} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PORSCHEenginelogo} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />





          <mesh name="Main_Body" geometry={nodes.Main_Body.geometry} material={materials.Porsche_Carrera_GT_Concept_2000_Replica_By_Alex_Ka} position={[-0.106, 3.081, 0.227]} rotation={[-0.006, 0, 0]} scale={4.998}>
            <meshStandardMaterial
              color={bodyColor}  // glossy black
              metalness={CarMetal}
              roughness={CarRough}
            />
          </mesh>


          {/* TOP RIGHT TYRE ref=-top_right_tyre_Ref-*/}
          <mesh name="top_right_tyre" geometry={nodes.top_right_tyre.geometry} material={materials.tire} position={[-4.347, 1.599, 6.712]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />
          <mesh name="top_right_tyre_outer" geometry={nodes.top_right_tyre_outer.geometry} material={materials.rim1} position={[-4.898, 1.599, 6.739]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} >
            <meshStandardMaterial
              color="#D4D7D9"
              metalness={1}
              roughness={0.05}
            />
          </mesh>
          <mesh name="top_right_tyre_inner" geometry={nodes.top_right_tyre_inner.geometry} material={materials.rim2} position={[-4.704, 1.554, 6.74]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} >
            <meshStandardMaterial
              color="#D4D7D9"
              metalness={1}
              roughness={0.05}
            />
          </mesh>
          <mesh name="top_right_tyre_branding" geometry={nodes.top_right_tyre_branding.geometry} material={materials.tireSIDE} position={[-4.347, 1.599, 6.739]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />

          {/* TOP LEFT TYRE ref=-top_left_tyre_Ref-*/}
          <mesh name="top_left_tyre" geometry={nodes.top_left_tyre.geometry} material={materials.tire} position={[4.335, 1.599, 6.768]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ></mesh>
          <mesh name="top_left_tyre_outer" geometry={nodes.top_left_tyre_outer.geometry} material={materials.rim1} position={[4.886, 1.599, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="top_left_tyre_inner" geometry={nodes.top_left_tyre_inner.geometry} material={materials.rim2} position={[4.692, 1.554, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="top_left_tyre_branding" geometry={nodes.top_left_tyre_branding.geometry} material={materials.tireSIDE} position={[4.335, 1.599, 6.741]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ></mesh>


          {/* BOTTOM LEFT TYRE ref=-top_left_tyre_Ref-*/}
          <mesh name="bottom_left_tyre" geometry={nodes.bottom_left_tyre.geometry} material={materials.tire} position={[4.143, 1.591, -7.244]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />
          <mesh name="bottom_left_tyre_outer" geometry={nodes.bottom_left_tyre_outer.geometry} material={materials.rim1} position={[4.815, 1.591, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="bottom_left_tyre_inner" geometry={nodes.bottom_left_tyre_inner.geometry} material={materials.rim2} position={[4.391, 1.543, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="bottom_left_tyre_branding" geometry={nodes.bottom_left_tyre_branding.geometry} material={materials.tireSIDE} position={[4.143, 1.591, -7.273]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />

          {/* BOTTOM RIGHT TYRE ref=-top_left_tyre_Ref-*/}
          <mesh name="bottom_right_tyre" geometry={nodes.bottom_right_tyre.geometry} material={materials.tire} position={[-4.151, 1.591, -7.303]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />
          <mesh name="bottom_right_tyre_outer" geometry={nodes.bottom_right_tyre_outer.geometry} material={materials.rim1} position={[-4.822, 1.591, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="bottom_right_tyre_inner" geometry={nodes.bottom_right_tyre_inner.geometry} material={materials.rim2} position={[-4.399, 1.544, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} ><meshStandardMaterial
            color="#D4D7D9"
            metalness={1}
            roughness={0.05}
          /></mesh>
          <mesh name="bottom_right_tyre_branding" geometry={nodes.bottom_right_tyre_branding.geometry} material={materials.tireSIDE} position={[-4.151, 1.591, -7.274]} rotation={[-0.006, 0, 0]} scale={4.998} visible={tyre1toggle} />


          {tyre1 && (
            <group name="Tyre_2" position={[4.05, 1.587, 6.754]} rotation={[-Math.PI / 2, 0, 0]} scale={0.032}>
              <group name="bottom_left_tyre001" position={[7.98, 433.818, 0]}>
                <mesh name="Object_2001" geometry={nodes.Object_2001.geometry} material={materials.RIM_UNITED} >

                </mesh>
                <mesh name="Object_3001" geometry={nodes.Object_3001.geometry} material={materials.RIM_UNITED} />
                <mesh name="Object_4003" geometry={nodes.Object_4003.geometry} material={materials['default']} />
              </group>
              <group name="bottom_right_tyre001" position={[-255.833, 433.818, 0]} rotation={[Math.PI, 0, 0]} scale={-1}>
                <mesh name="Object_2003" geometry={nodes.Object_2003.geometry} material={materials.RIM_UNITED} >

                </mesh>
                <mesh name="Object_3003" geometry={nodes.Object_3003.geometry} material={materials.RIM_UNITED} />
                <mesh name="Object_4005" geometry={nodes.Object_4005.geometry} material={materials['default']} />
              </group>
              <group name="top_left_tyre001" position={[7.98, 0, 0]}>
                <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.RIM_UNITED} >

                </mesh>
                <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.RIM_UNITED} />
                <mesh name="Object_4002" geometry={nodes.Object_4002.geometry} material={materials['default']} />
              </group>
              <group name="top_right_tyre001" position={[-255.833, 0, 0]} rotation={[Math.PI, 0, 0]} scale={-1}>
                <mesh name="Object_2002" geometry={nodes.Object_2002.geometry} material={materials.RIM_UNITED} >

                </mesh>
                <mesh name="Object_3002" geometry={nodes.Object_3002.geometry} material={materials.RIM_UNITED} />
                <mesh name="Object_4004" geometry={nodes.Object_4004.geometry} material={materials['default']} />
              </group>
            </group>
          )}

          {tyre2 && (
            <group name="Tyre_1" position={[0.302, -0.108, -1.034]} rotation={[-Math.PI / 2, 0, 0]} scale={4.88}>
              <group name="bottom_left_tyre002" position={[0, 2.885, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode003" position={[0.208, 0, 0]}>
                  <group name="mycar-wheelbrakeFtL002" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0001" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0001'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Plastic_0001" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0001'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Rims_0001" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0001'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Silver_0001" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0001'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0002" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0002'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0003" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0003'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                  </group>
                </group>
              </group>
              <group name="bottom_right_tyre002" position={[-0.125, 2.885, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01}>
                <group name="RootNode005" position={[0.208, 0, 0]}>
                  <group name="mycar-wheelbrakeFtL004" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0003" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0003'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Plastic_0003" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0003'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Rims_0003" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0003'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Silver_0003" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0003'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0006" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0006'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0007" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0007'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                  </group>
                </group>
              </group>
              <group name="top_left_tyre002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode002" position={[0.718, 0, 0]}>
                  <group name="mycar-wheelbrakeFtL001" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Plastic_0" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Rims_0" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Silver_0" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0001" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0001'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                  </group>
                </group>
              </group>
              <group name="top_right_tyre002" position={[-0.125, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01}>
                <group name="RootNode004" position={[0.718, 0, 0]}>
                  <group name="mycar-wheelbrakeFtL003" position={[83.782, 35.103, 159.133]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh name="mycar-wheelbrakeFtL001_Brake_Calipper_0002" geometry={nodes['mycar-wheelbrakeFtL001_Brake_Calipper_0002'].geometry} material={materials.Brake_Calipper} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Plastic_0002" geometry={nodes['mycar-wheelbrakeFtL001_Plastic_0002'].geometry} material={materials.Plastic} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Rims_0002" geometry={nodes['mycar-wheelbrakeFtL001_Rims_0002'].geometry} material={materials.Rims} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Silver_0002" geometry={nodes['mycar-wheelbrakeFtL001_Silver_0002'].geometry} material={materials.Silver} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0004" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0004'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                    <mesh name="mycar-wheelbrakeFtL001_Tyre_0005" geometry={nodes['mycar-wheelbrakeFtL001_Tyre_0005'].geometry} material={materials.Tyre} position={[0.001, -0.001, 0]} />
                  </group>
                </group>
              </group>
            </group>
          )}

          {tyre3 && (
            <group name="Tyre_3" position={[-3.257, 0, -7.284]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={4.122}>
              <group name="root001" position={[-0.015, 1.855, 0.388]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.879}>
                <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="CTWheelFtR_2" rotation={[-0.002, Math.PI / 2, 0]}>
                    <group name="rim004_0" position={[-0.187, 0.012, -0.006]}>
                      <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.007']} />
                    </group>
                    <group name="wheel002_1">
                      <mesh name="Object_10002" geometry={nodes.Object_10002.geometry} material={materials['Material.008']} />
                      <mesh name="Object_11001" geometry={nodes.Object_11001.geometry} material={materials['Material.008']} />
                      <mesh name="Object_12002" geometry={nodes.Object_12002.geometry} material={materials['Material.008']} />
                      <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['Material.008']} />
                      <mesh name="Object_8002" geometry={nodes.Object_8002.geometry} material={materials['Material.008']} />
                      <mesh name="Object_9001" geometry={nodes.Object_9001.geometry} material={materials['Material.008']} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="root002" position={[3.404, 1.855, 0.388]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.879}>
                <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="CTWheelFtR_2001" rotation={[-0.002, Math.PI / 2, 0]}>
                    <group name="rim004_0001" position={[-0.187, 0.012, -0.006]}>
                      <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['Material.007']} />
                    </group>
                    <group name="wheel002_1001">
                      <mesh name="Object_10003" geometry={nodes.Object_10003.geometry} material={materials['Material.008']} />
                      <mesh name="Object_11002" geometry={nodes.Object_11002.geometry} material={materials['Material.008']} />
                      <mesh name="Object_12003" geometry={nodes.Object_12003.geometry} material={materials['Material.008']} />
                      <mesh name="Object_7002" geometry={nodes.Object_7002.geometry} material={materials['Material.008']} />
                      <mesh name="Object_8003" geometry={nodes.Object_8003.geometry} material={materials['Material.008']} />
                      <mesh name="Object_9002" geometry={nodes.Object_9002.geometry} material={materials['Material.008']} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="root003" position={[-0.015, -0.273, 0.388]} scale={0.879}>
                <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="CTWheelFtR_2002" rotation={[-0.002, Math.PI / 2, 0]}>
                    <group name="rim004_0002" position={[-0.187, 0.012, -0.006]}>
                      <mesh name="Object_5002" geometry={nodes.Object_5002.geometry} material={materials['Material.007']} />
                    </group>
                    <group name="wheel002_1002">
                      <mesh name="Object_10004" geometry={nodes.Object_10004.geometry} material={materials['Material.008']} />
                      <mesh name="Object_11003" geometry={nodes.Object_11003.geometry} material={materials['Material.008']} />
                      <mesh name="Object_12004" geometry={nodes.Object_12004.geometry} material={materials['Material.008']} />
                      <mesh name="Object_7003" geometry={nodes.Object_7003.geometry} material={materials['Material.008']} />
                      <mesh name="Object_8004" geometry={nodes.Object_8004.geometry} material={materials['Material.008']} />
                      <mesh name="Object_9003" geometry={nodes.Object_9003.geometry} material={materials['Material.008']} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="root004" position={[3.404, -0.273, 0.388]} scale={0.879}>
                <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="CTWheelFtR_2003" rotation={[-0.002, Math.PI / 2, 0]}>
                    <group name="rim004_0003" position={[-0.187, 0.012, -0.006]}>
                      <mesh name="Object_5003" geometry={nodes.Object_5003.geometry} material={materials['Material.007']} />
                    </group>
                    <group name="wheel002_1003">
                      <mesh name="Object_10005" geometry={nodes.Object_10005.geometry} material={materials['Material.008']} />
                      <mesh name="Object_11004" geometry={nodes.Object_11004.geometry} material={materials['Material.008']} />
                      <mesh name="Object_12005" geometry={nodes.Object_12005.geometry} material={materials['Material.008']} />
                      <mesh name="Object_7004" geometry={nodes.Object_7004.geometry} material={materials['Material.008']} />
                      <mesh name="Object_8005" geometry={nodes.Object_8005.geometry} material={materials['Material.008']} />
                      <mesh name="Object_9004" geometry={nodes.Object_9004.geometry} material={materials['Material.008']} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          )}



          {/* FRONT GLASS */}
          <mesh name="front_mirror" geometry={nodes.front_mirror.geometry} material={materials.wfins} position={[-0.005, 4.692, 3.205]} rotation={[-0.006, 0, 0]} scale={4.998}>
            {/* <meshStandardMaterial
              color="#a0c8ff"         // light blue tint (you can adjust)
              metalness={0}           // glass isn’t metallic
              roughness={0.05}        // very smooth surface
              transparent={true}
              opacity={0.25}          // mostly transparent
              envMap="./hdri/1.hdr" // add your scene's env map for reflections
              envMapIntensity={1}     // reflection strength
              side={THREE.DoubleSide} // glass visible from both sides
            /> */}

          </mesh>

          {/* HEADLIGHT */}
          {/* LEFT HEADLIGHT */}
          <mesh name="left_head_light" geometry={nodes.left_head_light.geometry} material={materials.headlightglass} position={[3.497, 2.977, 9.821]} rotation={[-0.006, 0, 0]} scale={4.998}>
            <meshStandardMaterial
              color="#a0c8ff"         // light blue tint (you can adjust)
              metalness={0}           // glass isn’t metallic
              roughness={0.05}        // very smooth surface
              transparent={true}
              opacity={0.25}          // mostly transparent
              envMap="./hdri/1.hdr" // add your scene's env map for reflections
              envMapIntensity={1}     // reflection strength
              side={THREE.DoubleSide} // glass visible from both sides
            />
          </mesh>
          {/* RIGHT HEADLIGHT */}
          <mesh name="right_head_light" geometry={nodes.right_head_light.geometry} material={materials.headlightglass} position={[-3.505, 2.977, 9.822]} rotation={[-0.006, 0, 0]} scale={4.998}>
            {/* Glass Material */}
            <meshStandardMaterial
              color="#a0c8ff"
              metalness={0}
              roughness={0.05}
              transparent={true}
              opacity={0.25}
              envMapIntensity={1}
              side={THREE.DoubleSide}
            />




          </mesh>


          {/* FRONT SMALL LIGHT */}
          {/* LEFT */}
          <mesh name="front_small_light_left" geometry={nodes.front_small_light_left.geometry} material={materials.foglight} position={[2.433, 1.105, 11.462]} rotation={[-0.006, 0, 0]} scale={4.998} ></mesh>
          {/* RIGHT */}
          <mesh name="front_small_light_right" geometry={nodes.front_small_light_right.geometry} material={materials.foglight} position={[-2.446, 1.105, 11.461]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* FRONT BUMBER NET  */}
          <mesh name="front_bumper" geometry={nodes.front_bumper.geometry} material={materials.frontbumperplastic} position={[0.01, 1.048, 11.176]} rotation={[-0.006, 0, 0]} scale={4.998}>
            <meshStandardMaterial
              color="black"            // dark steel gray
              metalness={1}              // full metal reflection
              roughness={0.25}           // slight surface shine
              envMapIntensity={1.5}      // strong reflection if HDRI is used
              emissive="#000000"         // no self-glow    
            />

          </mesh>
          <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.grill2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998}></mesh>

          {/* BACK HEADLIGHT */}
          <mesh name="back_right_head_light" geometry={nodes.back_right_head_light.geometry} material={materials.brakelight} position={[-3.622, 3.431, -10.349]} rotation={[-0.006, 0, 0]} scale={4.998} >



          </mesh>
          <mesh name="back_left_head_light" geometry={nodes.back_left_head_light.geometry} material={materials.brakelight} position={[3.603, 3.431, -10.35]} rotation={[-0.006, 0, 0]} scale={4.998} >
          </mesh>
          <mesh name="back_middle_head_light" geometry={nodes.back_middle_head_light.geometry} material={materials.brakelight} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} >
          </mesh>

          {/* SIDE MIRRORS */}
          <mesh name="right_side_mirror" geometry={nodes.right_side_mirror.geometry} material={materials.sidemirrors} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} >
            <MeshReflectorMaterial
              resolution={1024}
              blur={[0, 0]}                // no blur — sharp reflections
              mixBlur={0}                  // no blend blur
              mixStrength={1}             // full reflection
              roughness={0}
              metalness={1}
              mirror={1}                   // true mirror effect
              depthScale={0.01}
              minDepthThreshold={0.9}
              maxDepthThreshold={1}
              color="#777"                 // slight base tint
              envMapIntensity={1}
            />

          </mesh>
          <mesh name="left_side_mirror" geometry={nodes.left_side_mirror.geometry} material={materials.sidemirrors} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} >
            <MeshReflectorMaterial
              resolution={1024}
              blur={[0, 0]}                // no blur — sharp reflections
              mixBlur={0}                  // no blend blur
              mixStrength={1}             // full reflection
              roughness={0}
              metalness={1}
              mirror={1}                   // true mirror effect
              depthScale={0.01}
              minDepthThreshold={0.9}
              maxDepthThreshold={1}
              color="#777"                 // slight base tint
              envMapIntensity={1}
            />


          </mesh>


          {/* LOGOS */}
          <mesh name="All_logos" geometry={nodes.All_logos.geometry} material={materials.emblem} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* NITROS */}
          <mesh name="right_nitro" geometry={nodes.right_nitro.geometry} material={materials.exhaustchrome} position={[-1.92, 1.928, -11.38]} rotation={[-0.006, 0, 0]} scale={4.998} >
            <meshStandardMaterial
              metalness={1}                 // fully metallic
              roughness={0.2}               // smooth with slight surface texture
              envMapIntensity={1.2}         // adds reflection from HDRI
              clearcoat={0.8}               // shiny coating like car paint
              clearcoatRoughness={0.05}     // very slight surface roughness
            />

          </mesh>
          <mesh name="left_nitro" geometry={nodes.left_nitro.geometry} material={materials.exhaustchrome} position={[1.914, 1.928, -11.379]} rotation={[-0.006, 0, 0]} scale={4.998} >
            <meshStandardMaterial
              metalness={1}                 // fully metallic
              roughness={0.2}               // smooth with slight surface texture
              envMapIntensity={1.2}         // adds reflection from HDRI
              clearcoat={0.8}               // shiny coating like car paint
              clearcoatRoughness={0.05}     // very slight surface roughness
            />

          </mesh>

          {/* MODEL 3D LOGO */}
          <mesh name="Camera_gt_logo" geometry={nodes.Camera_gt_logo.geometry} material={materials.CarreraGT} position={[-0.106, 3.214, -11.478]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* METALLIC SIDES SMALL */}
          <mesh name="car_black_metallic_sides" geometry={nodes.car_black_metallic_sides.geometry} material={materials.splitter} position={[-0.095, 0.379, 4.656]} rotation={[-0.006, 0, 0]} scale={4.998} >
            <meshStandardMaterial
              color="black"            // light gray metallic base (optional)
              metalness={0.9}
              roughness={0.0}
              envMapIntensity={1.0}
            />

          </mesh>


          {/* HEAD LIGHT SMALL LIGHTS */}
          <mesh name="back_net_behind_seat" geometry={nodes.back_net_behind_seat.geometry} material={materials.ENGINEgrill} position={[-0.006, 4.375, -5.714]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="top_right_head_light_big" geometry={nodes.top_right_head_light_big.geometry} material={materials.headlights1} position={[-3.884, 3.132, 9.045]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="top_left_head_light_big" geometry={nodes.top_left_head_light_big.geometry} material={materials.headlights1} position={[3.871, 3.132, 9.046]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="top_middle_head_light_big" geometry={nodes.top_middle_head_light_big.geometry} material={materials.headlights1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="top_right_head_light_small" geometry={nodes.top_right_head_light_small.geometry} material={materials.headlights2} position={[-3.213, 2.987, 9.433]} rotation={[-0.006, 0, 0]} scale={4.998} />
          <mesh name="top_left_head_light_small" geometry={nodes.top_left_head_light_small.geometry} material={materials.headlights2} position={[3.2, 2.987, 9.434]} rotation={[-0.006, 0, 0]} scale={4.998} />


          {/* BACK BOTH SMALL WINGS */}
          <mesh name="back_both_small_wings" geometry={nodes.back_both_small_wings.geometry} material={materials.enginehead} position={[-0.006, 4.587, -4.921]} rotation={[-0.006, 0, 0]} scale={4.998} />


          {/* UPPER TYRE */}
          <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.blackmatte} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} ></mesh>

          {/* UNDER WINGS  */}
          <mesh name="metallic_thing_under_wings" geometry={nodes.metallic_thing_under_wings.geometry} material={materials.enginechrome1} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* BLACK METALLIC STEERING  */}
          <mesh name="black_metallic_steering" geometry={nodes.black_metallic_steering.geometry} material={materials.interior} position={[0.916, 4.319, 1.712]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* STEERING SHEEL   */}
          <mesh name="interior_wheel" geometry={nodes.interior_wheel.geometry} material={materials.interiorplastic} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />


          {/* BEHIND NET CARPET  */}
          <mesh name="behind_net_carpet" geometry={nodes.behind_net_carpet.geometry} material={materials.floormat2} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* LEG CARPET  */}
          <mesh name="leg_carpet" geometry={nodes.leg_carpet.geometry} material={materials.floormat} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* BACK INNER MATERIAL  */}
          <mesh name="back_inner_material" geometry={nodes.back_inner_material.geometry} material={materials.engine} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />


          {/* SPOILERS */}
          {/* SPOILER 1  */}
          {spoiler1 && (
            <group name="Spoiler_1" position={[0, 5.491, -9.972]} rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
              <group name="4d8b5d19e0cb436896a422dbfd5fd5a2fbx" rotation={[Math.PI / 2, 0, 0]}>
                <group name="RootNode">
                  <group name="Universal_spoiler_1" rotation={[-Math.PI / 2, 0, 0]} scale={[100, 70.719, 100]}>
                    <mesh name="Universal_spoiler_1_Carbon_0" geometry={nodes.Universal_spoiler_1_Carbon_0.geometry} material={materials.Carbon} />
                    <mesh name="Universal_spoiler_1_Feet_0" geometry={nodes.Universal_spoiler_1_Feet_0.geometry} material={materials.Feet} />
                  </group>
                </group>
              </group>
            </group>
          )}
          <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.bottom} position={[-0.004, -0.118, 0.157]} rotation={[-0.006, 0, 0]} scale={4.998} />

          {/* SPOILER 2  */}
          {spoiler2 && (
            <group name="Spoiler_2" position={[0, 4.65, -8.81]} rotation={[-Math.PI / 2, 0, 0]} scale={0.624}>
              <group name="root">
                <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Cube001_0" position={[2.427, 0.018, -1.315]} rotation={[0.385, 0, 0]} scale={[0.051, 0.907, 0.442]}>
                    <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials.Material} position={[-1.54, 0, 0]} />
                  </group>
                  
                  <group name="Cube003_2" position={[6.009, 2.799, 0]} scale={[0.085, 0.926, 1.664]}>
                    <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['Material.003']} position={[-3.07, 0, 0]} />
                  </group>
                  <group name="Cube004_4" position={[-5.409, 2.799, 0]} scale={[0.085, 0.926, 1.664]}>
                    <mesh name="Object_12001" geometry={nodes.Object_12001.geometry} material={materials['Material.003']} position={[-3.07, 0, 0]} />
                  </group>
                  <group name="Cube005_5" position={[-1.393, 0.018, -1.315]} rotation={[0.385, 0, 0]} scale={[0.051, 0.907, 0.442]}>
                    <mesh name="Object_14001" geometry={nodes.Object_14001.geometry} material={materials.Material} position={[-17.884, 0, 0]} />
                  </group>
                  <group name="Cube_1" position={[0.317, 2.799, 0]} scale={[5.71, 0.055, 1.362]}>
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[-0.046, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          )}



          {/* SPOILER 3  */}
          {spoiler3 && (
            <group name="Spoiler_3" position={[0, 5.589, -9.666]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <group name="e79f5967d0b04bbf986de8022d9c6b9dfbx" rotation={[Math.PI / 2, 0, 0]}>
                <group name="RootNode001">
                  <group name="Plane" position={[0, -40.689, 3.731]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 16.373, 100]}>
                    <mesh name="Plane_Carbon_0" geometry={nodes.Plane_Carbon_0.geometry} material={materials['Carbon.001']} position={[0, 0.066, 0.063]} />
                    <mesh name="Plane_Feet_0" geometry={nodes.Plane_Feet_0.geometry} material={materials['Feet.001']} position={[0, 0.066, 0.063]} />
                  </group>
                </group>
              </group>
            </group>
          )}













          {/* METALLIC THINGS */}
          <mesh name="metallic_things2" geometry={nodes.metallic_things2.geometry} material={materials.turnsignalS} position={[-0.006, 3.327, 4.782]} rotation={[-0.006, 0, 0]} scale={4.998}>
            const metallicMaterial = (
            <meshStandardMaterial
              color="#777777"          // medium gray metallic color
              metalness={1}            // fully metallic
              roughness={0.25}         // slight roughness for realism
              envMapIntensity={1.3}    // decent reflection from environment
              side={THREE.DoubleSide}  // show both sides, just in case
            />
            );

          </mesh>

        </group>
      </group>
    </>
  )
}

useGLTF.preload('./model/Porche.glb')

export default Porche
